### ISSUE TITLE
Could not pass event BlockBreakEvent to AntiAura v11.02

### ISSUE THREAD

**Issue by CatNote** [EthanTG/AntiAura#90]
Our server version is 1.12.1 - PaperSpigot

[15:25:45] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AntiAura v11.02
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
	at a.bc.a(bc.java:3753) ~[AntiAura.jar:?]
	at a.bc.b(bc.java:3639) ~[AntiAura.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor927.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:192) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:872) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1172]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]

**Comment by EthanTG** [comment]
@CatNote Please follow the reporting format next time when you report! I'll leave this issue to Joe.

**Comment by CatNote** [comment]
Ok, Thanks.

**Comment by joehot200** [comment]
Fixed for 11.05.
