### ISSUE TITLE
bugs solved? Our server still have two bugs...

### ISSUE THREAD

**Issue by CatNote** [EthanTG/AntiAura#98]
**Screenshot (or video recording):** 

https://github.com/EthanTG/AntiAura/issues/90 -> Not Solved, occur with every blockbreaks
http://imgur.com/a/RUtol -> Player stuck while fly with fireworks

**AntiAura version:**

11.03

**Minecraft version:**

1.12.1

**Hacked Client (Set to N/A if none):**

N/A

**Description:**

[12:28:52] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AntiAura v11.03
java.lang.NoSuchMethodError: org.bukkit.entity.Player.getTargetBlock(Ljava/util/HashSet;I)Lorg/bukkit/block/Block;
	at a.bc.a(bc.java:3811) ~[AntiAura.jar:?]
	at a.bc.b(bc.java:3697) ~[AntiAura.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor322.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:514) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:290) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:192) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:872) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[PaperSpigot-latest.jar:git-Paper-1172]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_141]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [PaperSpigot-latest.jar:git-Paper-1172]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [PaperSpigot-latest.jar:git-Paper-1172]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_141]

[12:30:57] [Server thread/INFO]: Anonymous kicked for teleportation due to flying too far with Elytra.
[12:30:57] [Server thread/INFO]: Anonymous dragged back: Elytra distance.
[12:30:57] [Server thread/INFO]: Anonymous kicked for teleportation due to flying too far with Elytra.
[12:30:57] [Server thread/INFO]: Anonymous dragged back: Elytra distance.
[12:30:57] [Server thread/INFO]: Anonymous kicked for teleportation due to flying too far with Elytra.
[12:30:57] [Server thread/INFO]: Anonymous dragged back: Elytra distance.
[12:30:57] [Server thread/INFO]: Anonymous kicked for teleportation due to flying too far with Elytra.
[12:30:57] [Server thread/INFO]: Anonymous dragged back: Elytra distance.
[12:30:58] [Server thread/INFO]: Anonymous kicked for teleportation due to flying too far with Elytra.
[12:30:58] [Server thread/INFO]: Anonymous dragged back: Elytra distance.
[12:30:58] [Server thread/INFO]: Anonymous kicked for teleportation due to flying too far with Elytra.
[12:30:58] [Server thread/INFO]: Anonymous dragged back: Elytra distance.

**Comment by joehot200** [comment]
Despite the poor reporting format, are legitimate bugs afaik

**Comment by EthanTG** [comment]
*Edited format to become more smoother.*

Next time, could you use a repository like Pastebin or Hastebin to put your console logs in? Thanks! 

I'll let Joe figure this out.

**Comment by CatNote** [comment]
I was unfamiliar with the log storage site. Thank you for your advice.

**Comment by EthanTG** [comment]
No problem @CatNote ;)

**Comment by joehot200** [comment]
Fixed for 10.05
